#!/bin/bash

pushd `dirname $0`
sed -ri '/PLACEHOLDER_COMPILER_ARGS/ s/^.*$/git rev-parse HEAD/e; T; s/^.*$/$PreprocessorDefinitions "$BASE;DA_GIT_VERSION=\0"/' game/server/server_da.vpc
devtools/bin/vpc /da +game /mksln DoubleAction
popd
