#pragma once

typedef enum
{
	STYLE_POINT_SMALL,
	STYLE_POINT_LARGE,
	STYLE_POINT_STYLISH,
} style_point_t;

typedef enum {
	ANNOUNCEMENT_COOL,
	ANNOUNCEMENT_STYLISH,
	ANNOUNCEMENT_DIVE,
	ANNOUNCEMENT_DIVE_KILL,
	ANNOUNCEMENT_SLIDE,
	ANNOUNCEMENT_SLIDE_KILL,
	ANNOUNCEMENT_STUNT,
	ANNOUNCEMENT_STUNT_KILL,
	ANNOUNCEMENT_THROUGH_WALL,
	ANNOUNCEMENT_LAST_BULLET,
	ANNOUNCEMENT_LONG_RANGE,
	ANNOUNCEMENT_LONG_RANGE_KILL,
	ANNOUNCEMENT_DOUBLE_KILL,
	ANNOUNCEMENT_GRENADE,
	ANNOUNCEMENT_GRENADE_KILL,
	ANNOUNCEMENT_SLOWMO_KILL,
	ANNOUNCEMENT_TACTICOOL,
	ANNOUNCEMENT_BRAWL,
	ANNOUNCEMENT_BRAWL_KILL,
	TOTAL_ANNOUNCEMENTS
} announcement_t;
