"Resource/UI/SkillMenu.res"
{
	"buyequip_ct"
	{
		"ControlName"	"CSkillMenu"
		"fieldName"		"skill"
		"xpos"			"0"
		"ypos"			"0"
		"wide"			"550"
		"tall"			"400"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"	"0"
	}

	"skill_dab"
	{
		"ControlName"	"CDABSkillMenu"
		"fieldName"		"skill_dab"
		"xpos"			"0"
		"ypos"			"0"
		"wide"			"550"
		"tall"			"400"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"	"0"
	}
	"SkillInfo"
	{
		"ControlName"	"Panel"
		"fieldName"		"SkillInfo"
		"xpos"			"-10"
		"ypos"			"-10"
		"wide"			"0"
		"tall"			"0"
		"autoResize"		"3"
		"pinCorner"		"0"
		"visible"		"0"
		"enabled"		"0"
		"tabPosition"		"0"
	}
	"SkillInfoPanel"
	{
		"ControlName"	"CDABSkillInfoPanel"
		"fieldName"		"SkillInfoPanel"
		"xpos"			"300"
		"ypos"			"149"
		"wide"			"570"
		"tall"			"250"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"	"0"
		"font"			"MenuTitle3"
	}
	"SkillInfoBackground"
	{
		"ControlName"		"ImagePanel"
		"fieldName"		"SkillInfoBackground"
		"xpos"			"300"
		"ypos"			"149"
		"wide"			"570"
		"tall"			"250"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1" 
		"tabPosition"		"0"
		"fillcolor"		"SkillInfoBackground"
		"labelText"		""
	}
	"SysMenu"
	{
		"ControlName"		"Menu"
		"fieldName"		"SysMenu"
		"xpos"			"0"
		"ypos"			"0"
		"zpos"			"1"
		"wide"			"64"
		"tall"			"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"0"
		"enabled"		"0"
		"tabPosition"		"0"
		"font"			"BuyMenuDefault"
	}
	"ChooseSkill"
	{	
		"ControlName"		"Label"
		"fieldName"		"ChooseSkill"
		"xpos"			"10"
		"ypos"			"10"
		"wide"			"340"
		"tall"			"26"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"#DAB_SkillMenu_ChooseASkill"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"1"
		"font"			"MenuTitle"
		"FGColor"		"Label.TextBrightColor"
	}
	"ChooseSkillDescription"
	{	
		"ControlName"		"Label"
		"fieldName"		"ChooseSkillDescription"
		"xpos"			"10"
		"ypos"			"30"
		"wide"			"600"
		"tall"			"26"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"#DAB_SkillMenu_DescribeSkills"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"1"
		"font"			"BuyMenuDefault"
	}


	"skill_marksman"
	{
		"ControlName"	"SkillButton"
		"fieldName"		"skill_marksman"
		"xpos"			"10"
		"ypos"			"60"
		"wide"			"125"
		"tall"			"45"
		"autoResize"	"0"
		"pinCorner"		"2"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"	"0"
		"labelText"		"#DAB_Skill_Marksman"
		"textAlignment"	"center"
		"dulltext"		"0"
		"brighttext"	"1"
		"Command"		"setskill marksman"
		"Default"		"0"
		"font"			"DefaultSmall"
		"scaleImage"	"1"
		"activeimage"	"cls_blue_class6_active"
		"inactiveimage"	"cls_blue_class6"
	}

	"skill_adrenalinerush"
	{
		"ControlName"	"SkillButton"
		"fieldName"		"skill_adrenaline"
		"xpos"			"145"
		"ypos"			"60"
		"wide"			"125"
		"tall"			"45"
		"autoResize"	"0"
		"pinCorner"		"2"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"	"0"
		"labelText"		"#DAB_Skill_Adrenaline"
		"textAlignment"	"center"
		"dulltext"		"0"
		"brighttext"	"1"
		"Command"		"setskill adrenaline"
		"Default"		"0"
		"font"			"DefaultSmall"
		"scaleImage"	"1"
		"activeimage"	"cls_blue_class6_active"
		"inactiveimage"	"cls_blue_class6"
	}

	"skill_slowmo"
	{
		"ControlName"	"SkillButton"
		"fieldName"		"skill_slowmo"
		"xpos"			"280"
		"ypos"			"60"
		"wide"			"125"
		"tall"			"45"
		"autoResize"	"0"
		"pinCorner"		"2"
		"visible"		"1"
		"enabled"		"0"
		"tabPosition"	"0"
		"labelText"		"#DAB_Skill_Slowmo"
		"textAlignment"	"center"
		"dulltext"		"0"
		"brighttext"	"1"
		"Command"		"setskill slowmo"
		"Default"		"0"
		"font"			"DefaultSmall"
		"scaleImage"	"1"
		"activeimage"	"cls_blue_class6_active"
		"inactiveimage"	"cls_blue_class6"
	}

	"skill_secondwind"
	{
		"ControlName"	"SkillButton"
		"fieldName"		"skill_secondwind"
		"xpos"			"415"
		"ypos"			"60"
		"wide"			"125"
		"tall"			"45"
		"autoResize"	"0"
		"pinCorner"		"2"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"	"0"
		"labelText"		"#DAB_Skill_SecondWind"
		"textAlignment"	"center"
		"dulltext"		"0"
		"brighttext"	"1"
		"Command"		"setskill secondwind"
		"Default"		"0"
		"font"			"DefaultSmall"
		"scaleImage"	"1"
		"activeimage"	"cls_blue_class6_active"
		"inactiveimage"	"cls_blue_class6"
	}
}
